### ISSUE TITLE
회원가입시 유저정보 저장 로직의 문제점

### ISSUE THREAD

**Issue by profit0124** [DeveloperAcademy-POSTECH/MacC-Team-Sandals#58]
현재 구글의 경우 email 로 Document ID 를 지정, 애플의 경우 Authentication 생성시 uid 값으로 Document ID 값을 지정.
초기 이렇게 설정한 이유는 Apple의 경우 email 가리기 기능이 있으며, 또한 초기 애플에서 발행하는 토큰으로 Email 값을 확인하는 데 어려움이 있었음.

<img width="1083" alt="image" src="https://user-images.githubusercontent.com/31499563/202357345-f4da6c88-3bc5-414c-9f0c-4d093127cc9c.png">

유저의 정보를 가져올 때 Authentication 의 현재 로그인한 유저를 확인하여 email 값으로 gmail 인지, Apple인지 확인하여 유저 도큐먼트 아이디 값을 다르게 주고 있음. 
여기서 하나의 큰 문제가 있음. 만약 애플로그인에서 메일 주소 가리기를 하지 않을 경우, 애플 아이디 값이 gmail 주소값과 같을 수 있음.
즉 같은 메일 주소로 애플로그인, 구글로그인 둘다 생성할 수 있음.
이렇게 되면 애플로그인을 하였을 경우 구글로그인한 유저정보를 가지고 오게 됨.
즉, 고유값이 아닌 값으로 도큐먼트 아이디를 설정을 하는 로직으로 추후 서비스가 커질 경우 크게 문제가 될 수 있다고 판단되므로, 구글 로그인으로 가입할때도 Auth 의 uid 값으로 Document ID 를 생성할 필요가 있음.

**Comment by im-niber** [comment]
확인 했슴니당 ! ㅎㅇㅌ !
